name: CI/CD for Chisel Project

on:
  push:
    branches:
      - main
    pull_request:
      branches:
      - main

jobs:
  dec_p285_n255_k239:    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        bus-width: [4, 8, 16, 32, 64, 128]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true
      
    - name: build
      uses: ./.github/actions/chisel-build
      with:
        axis_clock: '156.25'
        core_clock: '156.25'
        symb_width: '8'
        bus_width: ${{ matrix.bus-width}}
        poly: '285'
        fcr: '0'
        n_len: '255'
        k_len: '239'

    - name: coco-sim
      uses: ./.github/actions/cocotb-sim

  dec_p285_n108_k106:    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        bus-width: [4, 8, 16, 32, 64, 108]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: true
      
    - name: build
      uses: ./.github/actions/chisel-build
      with:
        axis_clock: '156.25'
        core_clock: '156.25'
        symb_width: '8'
        bus_width: ${{ matrix.bus-width}}
        poly: '285'
        fcr: '0'
        n_len: '108'
        k_len: '106'

    - name: coco-sim
      uses: ./.github/actions/cocotb-sim
